#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "timestamp": "2026-06-03T01:33:00",
#     "name": "Cursor CLI",
#     "version": "2026.02.13-41ac335",
#     "model": "Claude 4.6 Opus (Thinking)",
#     "contribution": {
#       "value": 100,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker abstract metric item
  version: "1.0"
  summary: IVOA ExecutionBroker abstract metric item
  description: >-
    OpenAPI schema for abstract metric items in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    AbstractMetricItem:
      description: >-
        An abstract base class for a metric.
      type: object
      title: AbstractMetricItem
      required:
        - kind
      discriminator:
        propertyName: kind
        mapping:
          "https://www.purl.org/ivoa.net/Calycopis-openapi/schema/v1.0/kinds/metrics/abstract-metric-item.yaml": '#/components/schemas/AbstractMetricItem'
          "https://www.purl.org/ivoa.net/Calycopis-openapi/schema/v1.0/kinds/metrics/simple-minmax-float-metric.yaml": './simple-minmax-float-metric.yaml#/components/schemas/SimpleMinMaxFloatMetric'
      properties:
        kind:
          description: >-
            A URI identifier for the data model class.
          type: string
          format: uri
          xml:
            attribute: true
        type:
          description: >-
            A URI identifier for the type of metric.
            e.g. A URI representing a metric for compute or IO performance.
          type: string
          format: uri
        description:
          description: >-
            An optional description of the metric.
          type: string

    AbstractMetricItemList:
      description: >-
        A list of metrics.
      type: array
      title: AbstractMetricItemList
      xml:
        name: metrics
      items:
        $ref: '#/components/schemas/AbstractMetricItem'
        xml:
          name: metric
