#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2024, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker
  version: "1.0"
  summary: IVOA ExecutionBroker interface
  description: >-
    IVOA ExecutionBroker interface
  contact:
    name:  Dave Morris
    email: openapi.dev@dm92.uk
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0
servers:
  - url: http://localhost:8080
    description: Localhost development
paths:
  /offersets:
    post:
      operationId: OfferSetPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
          application/xml:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
          application/yaml:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
        required: true
      # TODO Errors return error codes and ErrorResponse.
      responses:
        "303":
          description: >-
            A redirect response to the '/offersets/{uuid}' endpoint.
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
        "200":
          description: >-
            A simple OK response with the offerset details.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/OfferSetResponse'
            application/xml:
              schema:
                $ref: './components.yaml#/components/schemas/OfferSetResponse'
            application/yaml:
              schema:
                $ref: './components.yaml#/components/schemas/OfferSetResponse'

  /offersets/{uuid}:
    get:
      operationId: OfferSetGet
      parameters:
        - name: uuid
          in: path
          description: >-
            The UUID identifier of the OfferSet.
          required: true
          schema:
            type: string
            format: uuid
          style: simple
      # TODO Errors return error codes and ErrorResponse.
      responses:
        "200":
          description: >-
            The set of responses for each content type.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/OfferSetResponse'
            application/xml:
              schema:
                $ref: './components.yaml#/components/schemas/OfferSetResponse'
            application/yaml:
              schema:
                $ref: './components.yaml#/components/schemas/OfferSetResponse'

  /sessions:
    post:
      operationId: DirectExecutionPost
      requestBody:
        description: >-
          A direct request to execute an execution without going through the offers process.
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
          application/xml:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
          application/yaml:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
        required: true

      responses:
        "303":
          description: >-
            303 See Other - The request was accepted, returning a redirect to the execution details.
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
        "200":
          description: >-
            200 OK - The request was accepted, returning the execution details.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/xml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/yaml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
        "400":
          description: >-
            400 Bad Request - The request was rejected, returning a FailedExecutionResponse
            with details of why the request was rejected.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/xml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/yaml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'

  /sessions/{uuid}:
    get:
      operationId: ExecutionSessionGet
      parameters:
        - name: uuid
          in: path
          description: >-
            The UUID identifier of the ExecutionSession.
          required: true
          schema:
            type: string
            format: uuid
          style: simple
      # TODO Errors return error codes and ErrorResponse.
      responses:
        "200":
          description: >-
            200 OK - Details of the selected execution.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/xml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/yaml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'

    post:
      operationId: ExecutionUpdatePost
      parameters:
        - name: uuid
          in: path
          description: >-
            The UUID identifier of the ExecutionSession.
          required: true
          schema:
            type: string
            format: uuid
          style: simple
      requestBody:
        required: true
        description: >-
          Details of the update request.
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/AbstractUpdate'
          application/xml:
            schema:
              $ref: './components.yaml#/components/schemas/AbstractUpdate'
          application/yaml:
            schema:
              $ref: './components.yaml#/components/schemas/AbstractUpdate'
      # TODO Errors return error codes and ErrorResponse.
      responses:
        "200":
          description: >-
            200 OK - Details of the updated execution.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/xml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'
            application/yaml:
              schema:
                $ref: './components.yaml#/components/schemas/AbstractExecutionSession'




