#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2025, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker volume mounts
  version: "1.0"
  summary: IVOA ExecutionBroker SimpleVolumeMount
  description: >-
    OpenAPI schema for a simple volume mount in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    SimpleVolumeMount:
      type: object
      title: SimpleVolumeMount
      description: >-
        A simple volume mount.
      allOf:
        - $ref: '../../components.yaml#/components/schemas/AbstractVolumeMount'
        - type: object
          properties:
            path:
              description: >
                The filesystem path.
              type: string
            mode:
              description: >
                The read-write access mode.
              type: string
              enum:
                - READONLY
                - READWRITE
            resource:
              description: >
                The resource to mount.
              type: string

