#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     },
#     {
#     "timestamp": "2026-03-25T12:00:00",
#     "name": "Cursor CLI",
#     "version": "2026.02.13-41ac335",
#     "model": "Claude 4.6 Opus (Thinking)",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker simple compute resource
  version: "1.0"
  summary: IVOA ExecutionBroker simple compute resource
  description: >-
    OpenAPI schema for a simple compute resource in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    SimpleComputeResource:
      type: object
      title: SimpleComputeResource
      description: >-
        A simple compute resource.
      allOf:
        - $ref: '../../components.yaml#/components/schemas/AbstractComputeResource'
        - type: object
          properties:
            cores:
              $ref: '#/components/schemas/SimpleComputeCores'
            memory:
              $ref: '#/components/schemas/SimpleComputeMemory'

    SimpleComputeCores:
      description: >-
        The number of CPU cores requested by the user.
        The minimum represents the lower limit that the excution requires.
        The maximum represents the highest number of cores that the excution can use.
      type: object
      title: SimpleComputeCores
#     allOf:
#       - $ref: '../../../components/utils.yaml#/components/schemas/MinMaxLong'
#       - $ref: '#/components/schemas/SimpleMinMaxLong'
#       - type: object
      properties:
        min:
          type: integer
          format: int64
        max:
          type: integer
          format: int64

    SimpleComputeMemory:
      description: >-
        The amount of memory requested by the user.
        The minimum represents the lower limit that the excution requires.
        The maximum represents the highest amount of memory that the excution can use.
        All values are given in multiples of 'GiB'.
      type: object
      title: SimpleComputeMemory
      properties:
        min:
          type: integer
          format: int64
        max:
          type: integer
          format: int64
#       units:
#         $ref: '../../../components/utils.yaml#/components/schemas/ComputeUnitsEnum'

#   SimpleVolumeMount:
#     type: object
#     title: SimpleVolumeMount
#     description: >-
#       A simple volume mount to expose storage or data resources as volumes in the compute resource filesystem.
#     properties:
#       path:
#         description: >
#           The filesystem mount point.
#         type: string
#       mode:
#         description: >
#           The read-write access mode.
#         type: string
#         enum:
#           - READONLY
#           - READWRITE
#       cardinality:
#         description: >
#           If cardinality is set to SINGLE, then this volume-mount will mount a single resource at the location set by the path.
#           If cardinality is set to CONTAINER, then this volume-mount will create a directory at the location set by the path,
#           and mount the resources within that directory.
#         type: string
#         enum:
#           - SINGLE
#           - CONTAINER
#       resources:
#         description: >
#           A list of the data resources to mount in this volume.
#           If cardinality is set to SINGLE then this list should only contain one resource.
#           If cardinality is set to SINGLE and this list has more than one resource, then it should fail validation.
#           If cardinality is set to CONTAINER then this list may contain more than one resource.
#         type: array
#         items:
#           type: string


