#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "timestamp": "2026-06-03T01:33:00",
#     "name": "Cursor CLI",
#     "version": "2026.02.13-41ac335",
#     "model": "Claude 4.6 Opus (Thinking)",
#     "contribution": {
#       "value": 100,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker simple min/max float cost
  version: "1.0"
  summary: IVOA ExecutionBroker simple min/max float cost
  description: >-
    OpenAPI schema for a simple min/max float cost in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    SimpleMinMaxFloatCost:
      description: >-
        A basic numeric minimum and maximum value for a cost.
        Both values are optional.
        The client can use this kind of cost to specify the maximum cost they are prepared to accept,
        and the service can quote the minimum and maximum that executing the task will cost.
      type: object
      title: SimpleMinMaxFloatCost
      allOf:
        - $ref: './abstract-cost-item.yaml#/components/schemas/AbstractCostItem'
        - type: object
          properties:
            min:
              description: >-
                The minimum cost value.
              type: number
              format: float
            max:
              description: >-
                The maximum cost value.
              type: number
              format: float
