#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: []
#
# A GitHub workflow to build and publish the Java client libraries.
#

name: Java client CI using Maven

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

jobs:

  build-java-client:

    runs-on: ubuntu-latest
    permissions:
      contents: read

#   env:
#     schemasource:  schema/v1.0/execution-broker.yaml
#     schemaversion: 1.0.2

    steps:

      # https://github.com/marketplace/actions/yaml-file-reader
      - name: Read the project config
        uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1
        with:
          yaml-file: config.yaml

      - name: Check the config
        run: |
          echo "schemasource  [${{ env.schemasource }}]"
          echo "schemaversion [${{ env.schemaversion }}]"

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # https://github.com/marketplace/actions/python-dependency-installation
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: isobeon/requirements.txt

      # https://github.com/marketplace/actions/yaml-file-reader
      # - name Read build settings from a YAML file ...
      #   uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1

      - name: Create build directory
        run: |
          mkdir --parents \
            build

      # ....
      - name: Run the schema processor
        run: |
          python \
            isobeon/schema-processor.py \
              ${{ env.schemasource }} \
              build/execution-broker-${{ env.schemaversion }}.yaml

      - name: Check result exists
        uses: andstor/file-existence-action@v3
        with:
          fail:  true
          files: build/execution-broker-${{ env.schemaversion }}.yaml

      - name: Check result content
        run: |
          head build/execution-broker-${{ env.schemaversion }}.yaml

      - name: Check result content
        run: |
          tail build/execution-broker-${{ env.schemaversion }}.yaml



