#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#       {
#       "name": "chatgpt",
#       "link": "https://chatgpt.com/share/6985cb44-51bc-8008-9259-cb9ff4530da5",
#       "contribution": {
#           "value": 1,
#           "units": "%"
#           }
#       },
#       {
#       "timestamp": "2026-03-25T12:00:00",
#       "name": "Cursor CLI",
#       "version": "2026.02.13-41ac335",
#       "model": "Claude 4.6 Opus (Thinking)",
#       "contribution": {
#           "value": 1,
#           "units": "%"
#           }
#       },
#       {
#       "timestamp": "2026-07-10",
#       "name": "chatgpt"
#       "link": "https://chatgpt.com/share/6a5124bf-6a34-83eb-aedc-2f92d5fd7b70"
#       "version": "2026.02.13-41ac335",
#       "contribution": {
#           "value": 1,
#           "units": "%"
#           }
#       }
#   ]
#
# A GitHub workflow to build and publish libraries from the schema.
#

name: Calycopis builder

on:
  push:
    branches:
      - 'main'

  pull_request:

  workflow_dispatch:

jobs:

  build-combined-schema:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Configure our versions
        run: |
            bin/versions.sh config.yaml
        shell: bash

      - name: Check the contents of GITHUB_ENV.
        run: |
          cat "${GITHUB_ENV}"
        shell: bash

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      # https://github.com/marketplace/actions/python-dependency-installation
      - name: Install Python dependencies
        run: |
            pip install -r \
              isobeon/requirements.txt

      - name: Run the schema processor
        run: |
          python \
            isobeon/schema-processor.py \
              'schema/${{env.schemashort}}/execution-broker.yaml' \
              '/tmp/${{env.combinedschema}}'

      - name: Check the result
        run: |
          head '/tmp/${{env.combinedschema}}'

      - name: Check the result
        run: |
          tail '/tmp/${{env.combinedschema}}'

      - name: Upload the schema file as a GitHub artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'calycopis-openapi-combined-schema'
          path: '/tmp/${{env.combinedschema}}'

  build-python-client:

    needs: build-combined-schema

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Download the combined schema
        uses: actions/download-artifact@v8
        with:
          name: 'calycopis-openapi-combined-schema'
          path: '/tmp'

      - name: Configure our versions
        run: |
            bin/versions.sh config.yaml
        shell: bash

      - name: Check the contents of GITHUB_ENV.
        run: |
          cat "${GITHUB_ENV}"
        shell: bash

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache our Maven dependencies
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run the Maven build
        run: |
          pushd 'codegen/python/client'
            ./mvnw \
              --batch-mode \
              clean generate-sources \
                -Drevision=${{env.pythonversion}} \
                -Dcalycopis.schema.file=/tmp/${{env.combinedschema}}
          popd

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install Python build tools
        run: |
            pip install \
                twine \
                build

      - name: Build the Python distribution
        run: |
          python -m \
            build \
                'codegen/python/client/target'

      - name: Upload the Python wheel as a GitHub artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'calycopis-openapi-python-client'
          path: 'codegen/python/client/target/dist/calycopis_schema_client-${{env.pythonversion}}-py3-none-any.whl'

  build-java-client:

    needs: build-combined-schema

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Download the combined schema
        uses: actions/download-artifact@v8
        with:
          name: 'calycopis-openapi-combined-schema'
          path: '/tmp'

      - name: Configure our versions
        run: |
            bin/versions.sh config.yaml
        shell: bash

      - name: Check the contents of GITHUB_ENV.
        run: |
          cat "${GITHUB_ENV}"
        shell: bash

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache our Maven dependencies
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run the Maven build
        run: |
          pushd 'codegen/java/client'
            ./mvnw \
              --batch-mode \
              clean generate-sources \
                -Drevision=${{env.javaversion}} \
                -Dcalycopis.schema.file=/tmp/${{env.combinedschema}}
          popd

      - name: Upload the Java JAR as a GitHub artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'calycopis-openapi-java-client'
          path: 'codegen/java/client/target/calycopis-schema-client-${{env.javaversion}}.jar'

  build-java-spring:

    needs: build-combined-schema

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Download the combined schema
        uses: actions/download-artifact@v8
        with:
          name: 'calycopis-openapi-combined-schema'
          path: '/tmp'

      - name: Configure our versions
        run: |
            bin/versions.sh config.yaml
        shell: bash

      - name: Check the contents of GITHUB_ENV.
        run: |
          cat "${GITHUB_ENV}"
        shell: bash

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache our Maven dependencies
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run the Maven build
        run: |
          pushd 'codegen/java/spring'
            ./mvnw \
              --batch-mode \
              clean generate-sources \
                -Drevision=${{env.javaversion}} \
                -Dcalycopis.schema.file=/tmp/${{env.combinedschema}}
          popd

      - name: Upload the Java JAR as a GitHub artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'calycopis-openapi-java-spring'
          path: 'codegen/java/spring/target/calycopis-schema-spring-${{env.javaversion}}.jar'

