#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: []
#
# A GitHub workflow to build and publish libraries from the schema.
#

name: Calycopis builder

on:
  push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:

  build-combined-schema:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      schemapath:    'v1.0'
      schemaversion: '1.0.2'

      openapiGeneratorName:    'openapi-generator-cli'
      openapiGeneratorVersion: '7.18.0'

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

#     # https://github.com/marketplace/actions/yaml-file-reader
#     - name: Read the project config
#       uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1
#       with:
#         yaml-file: config.yaml

      - name: Check the config
        run: |
          echo "schemapath    [${{env.schemapath}}]"
          echo "schemaversion [${{env.schemaversion}}]"

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # https://github.com/marketplace/actions/python-dependency-installation
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: isobeon/requirements.txt

      - name: Create the schema build directory
        run: |
          mkdir --parents \
            schema/build

      - name: Run the schema processor
        run: |
          python \
            isobeon/schema-processor.py \
              'schema/${{env.schemapath}}/execution-broker.yaml' \
              'schema/build/execution-broker-${{env.schemaversion}}.yaml'

      - name: Check result content
        run: |
          head 'schema/build/execution-broker-${{env.schemaversion}}.yaml'

      - name: Check result content
        run: |
          tail 'schema/build/execution-broker-${{env.schemaversion}}.yaml'

      - name: Upload the schema file
        uses: actions/upload-artifact@v4
        with:
          name: 'calycopis-schema'
          path: 'schema/build/'

  build-python-client:

    needs: build-combined-schema

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      schemapath:    'v1.0'
      schemaversion: '1.0.2'

      openapiGeneratorName:    'openapi-generator-cli'
      openapiGeneratorVersion: '7.18.0'

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

#     # https://github.com/marketplace/actions/yaml-file-reader
#     - name: Read the project config
#       uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1
#       with:
#         yaml-file: config.yaml

      - name: Check the config
        run: |
          echo "schemapath    [${{env.schemapath}}]"
          echo "schemaversion [${{env.schemaversion}}]"

      - name: Create the schema build directory
        run: |
          mkdir --parents \
            'schema/build/'

      - name: Download the schema result
        uses: actions/download-artifact@v4
        with:
          name: 'calycopis-schema'
          path: 'schema/build/'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Download the openapi-generator
        id: download-openapi-generator
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://repo1.maven.org'
          repository: 'maven2'
          groupId:    'org.openapitools'
          artifactId: 'openapi-generator-cli'
          version:    '${{env.openapiGeneratorVersion}}'
          extension:  'jar'

#     - name: Check file path
#       run: |
#         echo "File has been downloaded to [${{steps.download-openapi-generator.outputs.file}}]"

      - name: Create the Python build directory
        run: |
          mkdir --parents \
            'codegen/python/client/build'

      - name: Generate the Python client
        run: |
          java -jar '${{steps.download-openapi-generator.outputs.file}}' \
            generate \
            --generator-name python \
            --input-spec 'schema/build/execution-broker-${{env.schemaversion}}.yaml' \
            --output     'codegen/python/client/build' \
            --additional-properties 'projectName=calycopis-client' \
            --additional-properties 'packageName=calycopis_client' \
            --additional-properties 'packageUrl=https://github.com/ivoa/Calycopis-schema' \
            --additional-properties 'packageVersion=${{env.schemaversion}}'

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Python build tools
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            twine
            build

      - name: Build the Python distribution
        run: |
          python -m build \
            'codegen/python/client/build'

      - name: Upload the distribution wheel
        uses: actions/upload-artifact@v4
        with:
          name: 'calycopis-python-client'
          path: 'codegen/python/client/build/dist/calycopis_client-${{env.schemaversion}}-py3-none-any.whl'

  build-java-client:

    needs: build-combined-schema

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      schemapath:    'v1.0'
      schemaversion: '1.0.2'

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

#     # https://github.com/marketplace/actions/yaml-file-reader
#     - name: Read the project config
#       uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1
#       with:
#         yaml-file: config.yaml

      - name: Check the config
        run: |
          echo "schemapath    [${{env.schemapath}}]"
          echo "schemaversion [${{env.schemaversion}}]"

      - name: Download the schema result
        uses: actions/download-artifact@v4
        with:
          name: 'calycopis-schema'
          path: '/tmp'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Create properties file
        run: |
          pushd codegen/java/client
          cat > build.properties << EOF
          calycopis.schema.file=/tmp/execution-broker-${{env.schemaversion}}.yaml
          EOF
          popd

#     # https://github.com/marketplace/actions/maven-cache
#     - name: Restore our Maven cache
#       uses: skjolber/maven-cache-github-action@v3.1.1
#       with:
#         step: restore

      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache our Maven dependencies
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run the Maven build
        run: |
          pushd codegen/java/client
            ./mvnw --batch-mode install
          popd

#     # https://github.com/marketplace/actions/maven-cache
#     - name: Restore our Maven cache
#       uses: skjolber/maven-cache-github-action@v3.1.1
#       with:
#         step: save

      - name: Upload the JAR as a GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'calycopis-java-client'
          path: 'codegen/java/client/target/calycopis-client-${{env.schemaversion}}-SNAPSHOT.jar'

      - name: Publish the JAR to the GitHub Maven repository.
        if: ${{ github.repository == 'ivoa/Calycopis-schema' }}
        run: |
          pushd codegen/java/client
            ./mvnw --batch-mode deploy
          popd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-java-spring:

    needs: build-combined-schema

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      schemapath:    'v1.0'
      schemaversion: '1.0.2'

    steps:

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

#     # https://github.com/marketplace/actions/yaml-file-reader
#     - name: Read the project config
#       uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1
#       with:
#         yaml-file: config.yaml

      - name: Check the config
        run: |
          echo "schemapath    [${{env.schemapath}}]"
          echo "schemaversion [${{env.schemaversion}}]"

      - name: Download the schema result
        uses: actions/download-artifact@v4
        with:
          name: 'calycopis-schema'
          path: '/tmp'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Create properties file
        run: |
          pushd codegen/java/spring
          cat > build.properties << EOF
          calycopis.schema.file=/tmp/execution-broker-${{env.schemaversion}}.yaml
          EOF
          popd

#     # https://github.com/marketplace/actions/maven-cache
#     - name: Restore our Maven cache
#       uses: skjolber/maven-cache-github-action@v3.1.1
#       with:
#         step: restore

      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache our Maven dependencies
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run the Maven build
        run: |
          pushd codegen/java/spring
            ./mvnw --batch-mode install
          popd

#     # https://github.com/marketplace/actions/maven-cache
#     - name: Save our Maven cache
#       uses: skjolber/maven-cache-github-action@v3.1.1
#       with:
#         step: save

      - name: Upload the JAR as a GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'calycopis-java-spring'
          path: 'codegen/java/spring/target/calycopis-spring-${{env.schemaversion}}-SNAPSHOT.jar'

      - name: Publish the JAR to the GitHub Maven repository.
        if: ${{ github.repository == 'ivoa/Calycopis-schema' }}
        run: |
          pushd codegen/java/spring
            ./mvnw --batch-mode deploy
          popd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

