#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: []
#
# A GitHub workflow to build and publish the Java client libraries.
#

name: Java client CI using Maven

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

jobs:

  build-java-client:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      schemasource:  'schema/v1.0/execution-broker.yaml'
      schemaversion: '1.0.2'
      schematarget:  'build/execution-broker-1.0.2.yaml'

      openapiGeneratorName:    'openapi-generator-cli'
      openapiGeneratorVersion: '7.18.0'

    steps:

#     # https://github.com/marketplace/actions/yaml-file-reader
#     - name: Read the project config
#       uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1
#       with:
#         yaml-file: config.yaml

      - name: Check the config
        run: |
          echo "schemasource  [${{env.schemasource}}]"
          echo "schemaversion [${{env.schemaversion}}]"

      # https://github.com/actions/checkout
      - name: Checkout the schema project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Create the top level build directory
        run: |
          mkdir --parents \
            build

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # https://github.com/marketplace/actions/python-dependency-installation
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: isobeon/requirements.txt

      # https://github.com/marketplace/actions/yaml-file-reader
      # - name Read build settings from a YAML file ...
      #   uses: MangalAnkur/DevOpsPlanet-read-yaml-file@v1

      - name: Run the schema processor
        run: |
          python \
            isobeon/schema-processor.py \
              ${{env.schemasource}} \
              ${{env.schematarget}}

      - name: Check result content
        run: |
          head ${{env.schematarget}}

      - name: Check result content
        run: |
          tail ${{env.schematarget}}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Download the openapi-generator
        id: download-openapi-generator
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://repo1.maven.org'
          repository: 'maven2'
          groupId: 'org,openapitools'
          artifactId: 'openapi-generator-cli'
          version:    '${{env.openapiGeneratorVersion}}'
          extension:  'jar'

      - name: Check file path
        run: |
          echo "File has been downloaded to [${{steps.openapi-generator.outputs.file}}]"

      - name: Create the Python build directory
        run: |
          mkdir --parents \
            python/client/build

      - name: Generate the Python client
        run: |
          java -jar "${{steps.openapi-generator.outputs.file}}" \
            generate \
            --generator-name python \
            --input-spec "${{env.schematarget}}" \
            --output     "python/client/build" \
            --package-name "calycopis_openapi_client" \
            --additional-properties "packageUrl=https://github.com/ivoa/Calycopis-schema" \
            --additional-properties "packageVersion=${{schemaversion}}" \
            --additional-properties "projectName=calycopis-openapi-client"

      - name: Check the result
        run: |
          ls -al python/client/build





